apiVersion: batch/v1
kind: Job
metadata:
  name: bootiful-couchbase
  labels:
    name: bootiful-couchbase-pod
spec:
  template:
    metadata:
      name: bootiful-couchbase-pod
    spec:
      containers:
      - name: bootiful-couchbase
        image: arungupta/bootiful-couchbase
        imagePullPolicy: IfNotPresent
        env:
        - name: COUCHBASE_URI
          value: couchbase-service
      restartPolicy: Never

