apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    name: nginx
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx-rc-pod
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
