apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels: 
    name: nginx
spec: 
  containers: 
    - image: nginx
      imagePullPolicy: IfNotPresent
      name: nginx-pod
      ports: 
        - containerPort: 80
